[package]
name = "ftw"
version = "0.5.0"
authors = ["Michael Angelo Calimlim <macalimlim@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/macalimlim/ftw"
description = "A CLI tool to manage your godot-rust projects!"
keywords = ["godot", "godot-rust"]
categories = ["command-line-utilities", "game-development"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.39"
cargo-edit = "0.7.0"
cargo-generate = "0.6.0"
clap = "3.0.0-beta.2"
fs_extra = "1.2.0"
kstring = "1.0.1"
liquid = "0.22.0"
liquid-core = "0.22.0"
regex = "1.4.5"
rust-ini = "0.16.1"
strum = "0.20"
strum_macros = "0.20"
thiserror = "1.0.24"
voca_rs = "1.13.0"
walkdir = "2.3.2"

[dev-dependencies]
assert_cmd = "1.0.3"
cargo-edit = "0.7.0"
nanoid = "0.3.0"
predicates = "1.0.7"
remove_dir_all = "0.7.0"

[profile.release]
lto = false
